version: '3'

volumes:
  rocketconnect_local_postgres_data: {}
  rocketconnect_local_postgres_data_backups: {}
  evolution_local_store: {}
  evolution_local_instances: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: rocketconnect_local_django
    container_name: rocketconnect_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start
    networks:
       default:
          aliases:
            - django.local
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: rocketconnect_production_postgres
    container_name: rocketconnect_local_postgres
    volumes:
      - rocketconnect_local_postgres_data:/var/lib/postgresql/data
      - rocketconnect_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: rocketconnect_local_docs
    container_name: rocketconnect_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./rocket_connect:/app/rocket_connect:z
    ports:
      - '9000:7000'
    command: /start-docs

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: rocketconnect_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: docker.io/redis:6
    container_name: rocketconnect_local_redis

  celeryworker:
    <<: *django
    image: rocketconnect_local_celeryworker
    container_name: rocketconnect_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: rocketconnect_local_celerybeat
    container_name: rocketconnect_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: rocketconnect_local_flower
    container_name: rocketconnect_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  evolution:
    image: davidsongomes/evolution-api
    restart: always
    ports:
      - 8084:8080
    volumes:
      - evolution_local_instances:/evolution/instances
      - evolution_local_store:/evolution/store
    env_file:
      - ./compose/local/evolution/env
    command: ['node', './dist/src/main.js']
