# Generated by Django 3.1.10 on 2021-06-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asterisk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='answred',
            new_name='answered',
        ),
        migrations.AlterField(
            model_name='call',
            name='agent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='queue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
