# Generated by Django 3.1.10 on 2021-06-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asterisk', '0002_auto_20210611_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='caller_left_queue',
            field=models.BooleanField(default=False),
        ),
    ]
