# Generated by Django 3.1.7 on 2021-04-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[['incoming', 'Income Message, Raw Message is from Client, Payload to Rocketchat'], ['outgoing', 'Outgoing Message, Raw Message is from Rocket Connect, payload is to Client']], default='incoming', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='raw_message',
            field=models.JSONField(blank=True, help_text='the message that first came to be connected', null=True),
        ),
    ]
