# Generated by Django 3.1.7 on 2021-04-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0003_auto_20210404_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='payload',
            field=models.JSONField(blank=True, help_text='the message that goes gout, after processed', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[['incoming', 'Incoming Message'], ['ingoing', 'Ingoing Message']], default='incoming', max_length=50),
        ),
    ]
