# Generated by Django 3.2.13 on 2022-05-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0006_auto_20210420_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[['incoming', 'Incoming Message'], ['ingoing', 'Ingoing Message'], ['active_chat', 'Active Chat']], default='incoming', max_length=50),
        ),
    ]
