# Generated by Django 3.2.13 on 2022-05-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0007_alter_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ack',
            field=models.BooleanField(default=False),
        ),
    ]
