# Generated by Django 3.1.7 on 2021-04-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0003_server_secret_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connector',
            name='token',
        ),
        migrations.AlterField(
            model_name='connector',
            name='name',
            field=models.CharField(help_text='Connector Name, ex: LAB PHONE (+55 33 9 99851212)', max_length=50),
        ),
    ]
