# Generated by Django 3.1.7 on 2021-04-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0007_auto_20210420_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
