# Generated by Django 3.1.10 on 2021-06-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0008_connector_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='admin_user_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='admin_user_token',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='bot_user_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='bot_user_token',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
