# Generated by Django 3.1.10 on 2021-07-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0009_auto_20210602_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='secondary_connectors',
            field=models.ManyToManyField(blank=True, related_name='_connector_secondary_connectors_+', to='instance.Connector'),
        ),
    ]
