# Generated by Django 3.2.13 on 2022-05-18 21:26

from django.db import migrations, models
import instance.models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0011_auto_20220518_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='external_token',
            field=models.CharField(default=instance.models.random_string, help_text='This field is used to link the actual server', max_length=50, unique=True),
        ),
    ]
