# Generated by Django 3.2.13 on 2022-05-18 21:33

from django.db import migrations, models
import instance.models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0012_alter_server_external_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='external_token',
            field=models.CharField(default=instance.models.random_string, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='external_url',
            field=models.CharField(blank=True, help_text='This field is used to link to actual server', max_length=150),
        ),
    ]
