# Generated by Django 3.2.13 on 2022-07-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0014_alter_server_external_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='admin_password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='server',
            name='admin_user',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='server',
            name='bot_password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='server',
            name='bot_user',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
