# Generated by Django 3.2.13 on 2022-07-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('instance', '0015_auto_20220722_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='server_tasks',
            field=models.ManyToManyField(to='django_celery_beat.PeriodicTasks'),
        ),
    ]
