# Generated by Django 3.2.13 on 2022-07-23 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0016_server_server_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='server_tasks',
            new_name='tasks',
        ),
    ]
