# Generated by Django 3.2.13 on 2022-08-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0019_alter_server_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Connector General configutarion', null=True),
        ),
    ]
