# Generated by Django 3.2.13 on 2023-01-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0022_customdefaultmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdefaultmessages',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
