# Generated by Django 3.2.13 on 2023-05-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0023_customdefaultmessages_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdefaultmessages',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
