# Generated by Django 3.2.13 on 2023-05-03 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0024_customdefaultmessages_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customdefaultmessages',
            options={'ordering': ['order'], 'verbose_name': 'CustomMessages', 'verbose_name_plural': 'Custom Messagess'},
        ),
    ]
