# Generated by Django 3.2.13 on 2023-05-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0025_alter_customdefaultmessages_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='type',
            field=models.TextField(choices=[('rocketchat', 'Rocket.Chat'), ('chatwoot', 'Chatwoot')], default='rocketchat'),
        ),
    ]
