# Generated by Django 3.2.13 on 2023-05-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0026_server_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='default_messages',
        ),
        migrations.AddField(
            model_name='server',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='General Config for this Server', null=True),
        ),
    ]
