# Generated by Django 3.1.7 on 2021-04-03 20:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('url', models.CharField(max_length=150)),
                ('admin_user', models.CharField(max_length=50)),
                ('admin_password', models.CharField(max_length=50)),
                ('bot_user', models.CharField(max_length=50)),
                ('bot_password', models.CharField(max_length=50)),
                ('managers', models.CharField(help_text='separate users with comma, eg: user1,user2,user3', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
            },
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(help_text='Connector Name', max_length=50)),
                ('token', models.CharField(help_text='Connector Token that is aggregated to visitor token', max_length=50)),
                ('connector_type', models.CharField(max_length=50)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('managers', models.CharField(blank=True, help_text='separate users with comma, eg: user1,user2,user3', max_length=50, null=True)),
                ('config', models.JSONField(blank=True, help_text='Connector General configutarion', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='instance.server')),
            ],
            options={
                'verbose_name': 'Connector',
                'verbose_name_plural': 'Connector',
            },
        ),
    ]
