# Generated by Django 3.1.7 on 2021-03-21 11:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('url', models.URLField(max_length=500)),
                ('admin_user', models.CharField(max_length=50)),
                ('admin_password', models.CharField(max_length=50)),
                ('bot_user', models.CharField(max_length=50)),
                ('bot_password', models.CharField(max_length=50)),
                ('managers', models.CharField(help_text='separate users with comma, eg: user1,user2,user3', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
            },
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connector_type', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='instance.server')),
            ],
            options={
                'verbose_name': 'Connector',
                'verbose_name_plural': 'Connector',
            },
        ),
    ]
