# Generated by Django 3.1.7 on 2021-03-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='url',
            field=models.CharField(max_length=150),
        ),
    ]
