# Generated by Django 3.1.7 on 2021-04-03 21:16

from django.db import migrations, models
import instance.models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='external_token',
            field=models.CharField(default=instance.models.random_string, max_length=50),
        ),
    ]
