# Generated by Django 3.1.7 on 2021-03-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0002_auto_20210321_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='name',
            field=models.CharField(default='Default Connector Name', max_length=50),
            preserve_default=False,
        ),
    ]
