# Generated by Django 3.1.7 on 2021-03-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0003_connector_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='token',
            field=models.CharField(default='instancia-geral', help_text='Connector Token that is aggregated to visitor token', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='connector',
            name='name',
            field=models.CharField(help_text='Connector Name', max_length=50),
        ),
    ]
