# Generated by Django 3.1.7 on 2021-03-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0004_auto_20210330_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
