# Generated by Django 3.1.7 on 2021-04-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0005_connector_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='managers',
            field=models.CharField(blank=True, help_text='separate users with comma, eg: user1,user2,user3', max_length=50, null=True),
        ),
    ]
