# Generated by Django 3.1.7 on 2021-04-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0006_connector_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='config',
            field=models.JSONField(blank=True, help_text='Connector General configutarion', null=True),
        ),
    ]
