# Generated by Django 3.1.7 on 2021-03-21 11:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='instance.connector')),
            ],
            options={
                'verbose_name': 'Live Chat Room',
                'verbose_name_plural': 'Live Chat Rooms',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('envelope_id', models.CharField(max_length=100)),
                ('message_payload', models.JSONField()),
                ('response', models.JSONField()),
                ('delivered', models.BooleanField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='instance.connector')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='envelope.livechatroom')),
            ],
            options={
                'verbose_name': 'Envelope',
                'verbose_name_plural': 'Envelopes',
            },
        ),
    ]
