# Generated by Django 3.1.7 on 2021-04-04 02:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instance', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('token', models.CharField(blank=True, max_length=50, null=True)),
                ('room_id', models.CharField(blank=True, max_length=50, null=True)),
                ('open', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='instance.connector')),
            ],
            options={
                'verbose_name': 'Live Chat Room',
                'verbose_name_plural': 'Live Chat Rooms',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('envelope_id', models.CharField(max_length=100)),
                ('raw_message', models.JSONField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('delivered', models.BooleanField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='instance.connector')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='envelope.livechatroom')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ('created',),
            },
        ),
    ]
