# Generated by Django 3.1.7 on 2021-03-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_payload',
        ),
        migrations.AddField(
            model_name='message',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='response',
            field=models.JSONField(blank=True),
        ),
    ]
