# Generated by Django 3.1.7 on 2021-03-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0002_auto_20210321_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
