# Generated by Django 3.1.7 on 2021-04-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0002_auto_20210404_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[['incoming', 'Incoming Message'], ['outgoing', 'Outgoing Message']], default='incoming', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('envelope_id', 'type')},
        ),
    ]
