# Generated by Django 3.1.7 on 2021-04-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0004_auto_20210408_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='payload',
            field=models.JSONField(blank=True, default=dict, help_text='the message that goes gout, after processed', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='response',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
