# Generated by Django 3.1.7 on 2021-03-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0008_auto_20210321_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='livechatroom',
            name='open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livechatroom',
            name='room_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='livechatroom',
            name='token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
