# Generated by Django 3.1.10 on 2021-06-11 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=50, unique=True)),
                ('answred', models.DateTimeField(blank=True, null=True)),
                ('hangup', models.DateTimeField(blank=True, null=True)),
                ('queue', models.CharField(max_length=50)),
                ('agent', models.CharField(max_length=50)),
                ('caller', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('previous_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asterisk.call')),
            ],
            options={
                'verbose_name': 'Call',
                'verbose_name_plural': 'Calls',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='CallMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='asterisk.call')),
            ],
        ),
    ]
